version: '3.8'

services:
  postgres:
    container_name: dayflow-postgres
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dayflow_db
    ports:
      - "5433:5432"
    volumes:
      - dayflow_pgdata:/var/lib/postgresql/data

volumes:
  dayflow_pgdata:
